### ISSUE TITLE
timezone aware of get_sun_position()

### ISSUE THREAD

**Issue by Raymundo1** [sustainablecomputinglab/solar-tk#1]
https://github.com/sustainablecomputinglab/solar-tk/blob/97bde13d1e8c519965feb0d51be2aebd1a05ba4d/solartk/parameters.py#L72-L75

Since you change the start time and end time to UTC timezone before running get_sun_position(). Do you have to change them back after getting the sun position? It seems like in the implementation of get_sun_position(), you do not change the time back to current time zone.

**Comment by noman-bashir** [comment]
No. The start_time and end_time are converted to UTC only for the scope of get_sun_position() function, which needs time in UTC for its calculations. The data returned from the get_sun_position() function does not contain any time information. Instead, the zenith and azimuth angles are appended as new columns to the "data" dataframe that contains the provided historical solar data. Of course, this assumes that the data provided by the user does not have any missing time stamp.
